FROM node:alpine

WORKDIR /app

# Add package files
COPY package.json ./

# Install dependecies
RUN npm install

# Copy source
COPY src ./src
COPY tsconfig.json ./tsconfig.json

# Build dist
RUN npm run build

COPY . .

CMD ["npm", "run", "dev"]




