version: '3'

services:
  redis:
    image: 'redis:latest'
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    volumes:
      - ./cache:/data/cache
  mongo:
    image: mongo:latest
    container_name: api_mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    depends_on:
      - mongo
      - redis
    volumes:
      - /app/node_modules
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://api_mongo:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PW=sOmE_sEcUrE_pAsS
    env_file:
      - .env
